services:
  app:
    build:
      context: .
      dockerfile: docker/Dockerfile
    image: tturkowski/fruits-and-vegetables
    container_name: fruits_and_vegetables_app_container
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    networks:
      - app_network
    depends_on:
      - redis

  redis:
    image: redis:6.2
    container_name: fruits_and_vegetables_redis_container
    networks:
      - app_network
    volumes:
      - redis-data:/data
    ports:
      - "6379:6379"

networks:
  app_network:
    driver: bridge

volumes:
  redis-data:
    driver: local
